In [1]:
import numpy as np
import pandas as pd 


df = pd.read_csv("adult.data.csv")
df = pd.DataFrame(df)
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [28]:
higher_education = df['education'].isin(['Bachelors','Masters' ,'Doctorate']).mean() * 100
lower_education = (~df['education'].isin(['Bachelors','Masters' ,'Doctorate'])).mean() * 100

In [ ]:
lower_education_rich = (~df[(df['salary'] == '>50K') & (~df['education'].isin(['Bachelors','Masters' ,'Doctorate']))]).mean()
lower_education_rich

TypeError: bad operand type for unary ~: 'str'

In [30]:
lower_education

76.99394981726606

In [ ]:
rich = higher_education

In [23]:
df['salary'] == '>50K'

0        False
1        False
2        False
3        False
4        False
         ...
32556    False
32557     True
32558    False
32559    False
32560     True
Name: salary, Length: 32561, dtype: bool

In [22]:
lower_education

13.374896348392248

In [4]:
df['salary'].value_counts()

salary
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [ ]:
len(df)

32561

In [36]:
df['hours-per-week'].min()

1

In [39]:
(df['salary'] == '>50K') & (df['hours-per-week'] == 1)

0        False
1        False
2        False
3        False
4        False
         ...
32556    False
32557    False
32558    False
32559    False
32560    False
Length: 32561, dtype: bool

In [ ]:
top_IN_occupation = df[(df['salary'] == '>50K') & (df['native-country'] == 'India')].value_counts().get('occupation')
top_IN_occupation

In [98]:
n = df[df['salary'] == '>50K']['education'].isin(['Bachelors','Masters' ,'Doctorate'])
len(n)
#higher_education
#higher_education_rich = higher_education['salary'] == '>50K'

7841

In [87]:
df.columns[:4]
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [70]:
i = 0 
c = 0 

while True:
    i +=1 
    if i == 10 :
        c+=1 
        i=0
    if c==3:
        print('bow')
        continue

bow
bow
bow
bow
bow
bow
bow
bow
bow
bow

KeyboardInterrupt: